const products = [
  {
    _id: '1',
    name: 'Baseball Ball',
    image: '/images/baseball.jpg',
    description:
      'High-quality PVC leather cover and cork filling, providing certain softness and comfortable touch feeling. The safety baseballs have a soft, cushioned construction which can reduce impact produced during ball catching.',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Cricket Bat',
    image: '/images/bat.jpg',
    description:
      'Perfectly balanced with high performance this is the perfect bat for the player who likes to play big entertaining shots',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Football',
    image: '/images/footballs.jpg',
    description:
      'The deep-pebble surface material and pro style raised laces ensure extra traction which makes the footballs easy to throw and catch',
    brand: 'Cannon',
    category: 'Electronics',
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Boxing Gloves',
    image: '/images/glove.jpg',
    description:
      'Shock-absorbing high-density foam padding; fully attached thumb for better injury protection',
    brand: 'Sony',
    category: 'Electronics',
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Baseball Helmet',
    image: '/images/helmet.jpg',
    description:
      'To protect the players heads, the helmet has an EVA impact foam interior, a strong and durable ABS shell and an elastic nylon chin strap.',
    brand: 'Logitech',
    category: 'Electronics',
    price: 49.99,
    countInStock: 7,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Baseball Gloves',
    image: '/images/gloves.jpg',
    description:
      'Contour fit System provides customizable finger adjustments',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Hockey Stick',
    image: '/images/hockeyy.jpg',
    description:
      'The even balanced weight distribution provides a great feel for stickhandling, passing, and shooting.',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '8',
    name: 'Vollyball',
    image: '/images/vollyball.jpg',
    description:
      '18-panel, machine-sewn construction for optimal shape retention',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '9',
    name: 'Table Tennis - Paddle & ball set',
    image: '/images/table_tennis.jpg',
    description:
      ' The handles come in a flared design (narrower at top and wider at bottom) which not only offers superior grip on the blade but also offers enough flexibility. ',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: '10',
    name: 'Vollyball Net',
    image: '/images/net.jpg',
    description:
      'The volleyball net is made with high tenacity resistant nylon for superior shape retention and durability. A 0.11-inch thickness plastic coated steel wire runs through the upper border of the volleyball net for more stability. The high-quality construction ensures that the products will last years to use.',
    brand: 'Amazon',
    category: 'Electronics',
    price: 29.99,
    countInStock: 0,
    rating: 3.5,
    numReviews: 12,
  },
]

module.exports = products
